// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GeneralButton: typeof import('./src/components/Element/GeneralButton.vue')['default']
    MainContainer: typeof import('./src/components/Layout/MainContainer.vue')['default']
    MainFooter: typeof import('./src/components/Element/MainFooter.vue')['default']
    MapBox: typeof import('./src/components/Exclusive/MapBox.vue')['default']
    NavBar: typeof import('./src/components/Element/NavBar.vue')['default']
    NeonTexture: typeof import('./src/components/Texture/NeonTexture.vue')['default']
    ProcedureBar: typeof import('./src/components/Exclusive/ProcedureBar.vue')['default']
    ScreenTone: typeof import('./src/components/Layout/ScreenTone.vue')['default']
    SpotlightBox: typeof import('./src/components/Layout/SpotlightBox.vue')['default']
  }
}
