// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MainContainer: typeof import('./src/components/Layout/MainContainer.vue')['default']
    ScreenTone: typeof import('./src/components/Layout/ScreenTone.vue')['default']
  }
}
