/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GeneralButton: typeof import('./src/components/Element/GeneralButton.vue')['default']
    MainContainer: typeof import('./src/components/Layout/MainContainer.vue')['default']
    MainFooter: typeof import('./src/components/Element/MainFooter.vue')['default']
    MapBox: typeof import('./src/components/Exclusive/MapBox.vue')['default']
    NavBar: typeof import('./src/components/Element/NavBar.vue')['default']
    NeonTexture: typeof import('./src/components/Texture/NeonTexture.vue')['default']
    ProcedureBar: typeof import('./src/components/Exclusive/ProcedureBar.vue')['default']
    ScreenTone: typeof import('./src/components/Layout/ScreenTone.vue')['default']
    SpotlightBox: typeof import('./src/components/Layout/SpotlightBox.vue')['default']
  }
}
